"""add_phase1_settings

Revision ID: 161cac564015
Revises: 5e045bdb36b2
Create Date: 2026-07-22 13:03:31.650894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '161cac564015'
down_revision: Union[str, None] = '5e045bdb36b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('working_hours', sa.String(length=100), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id')
    )
    op.create_index(op.f('ix_hospital_settings_created_at'), 'hospital_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_hospital_settings_id'), 'hospital_settings', ['id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('sms_on_appointment', sa.Boolean(), nullable=False),
    sa.Column('email_on_appointment', sa.Boolean(), nullable=False),
    sa.Column('sms_on_billing', sa.Boolean(), nullable=False),
    sa.Column('email_on_billing', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id')
    )
    op.create_index(op.f('ix_notification_settings_created_at'), 'notification_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    op.create_table('user_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('theme', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('email_notifications', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_preferences_created_at'), 'user_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_preferences_id'), 'user_preferences', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_id'), table_name='user_preferences')
    op.drop_index(op.f('ix_user_preferences_created_at'), table_name='user_preferences')
    op.drop_table('user_preferences')
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_index(op.f('ix_notification_settings_created_at'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_hospital_settings_id'), table_name='hospital_settings')
    op.drop_index(op.f('ix_hospital_settings_created_at'), table_name='hospital_settings')
    op.drop_table('hospital_settings')
    # ### end Alembic commands ###
