"""check_missing_tables

Revision ID: 5e045bdb36b2
Revises: b2c3d4e5f6a7
Create Date: 2026-07-21 17:48:03.443610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

revision: str = '5e045bdb36b2'
down_revision: Union[str, None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_deleted'), 'notifications', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notifications_priority'), 'notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_notifications_reference_id'), 'notifications', ['reference_id'], unique=False)
    op.create_index(op.f('ix_notifications_reference_type'), 'notifications', ['reference_type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('doctor_medical_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('report_title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.String(length=100), nullable=False),
    sa.Column('diagnosis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctor_medical_records_created_at'), 'doctor_medical_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_doctor_medical_records_doctor_id'), 'doctor_medical_records', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_doctor_medical_records_id'), 'doctor_medical_records', ['id'], unique=False)
    op.create_index(op.f('ix_doctor_medical_records_patient_id'), 'doctor_medical_records', ['patient_id'], unique=False)
    op.create_table('nurse_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nurse_attendance_attendance_date'), 'nurse_attendance', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_nurse_attendance_created_at'), 'nurse_attendance', ['created_at'], unique=False)
    op.create_index(op.f('ix_nurse_attendance_id'), 'nurse_attendance', ['id'], unique=False)
    op.create_index(op.f('ix_nurse_attendance_nurse_id'), 'nurse_attendance', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_nurse_attendance_status'), 'nurse_attendance', ['status'], unique=False)
    op.create_table('nurse_patient_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('patient_status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nurse_patient_assignments_created_at'), 'nurse_patient_assignments', ['created_at'], unique=False)
    op.create_index(op.f('ix_nurse_patient_assignments_id'), 'nurse_patient_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_nurse_patient_assignments_nurse_id'), 'nurse_patient_assignments', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_nurse_patient_assignments_patient_id'), 'nurse_patient_assignments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_nurse_patient_assignments_patient_status'), 'nurse_patient_assignments', ['patient_status'], unique=False)
    op.create_index(op.f('ix_nurse_patient_assignments_status'), 'nurse_patient_assignments', ['status'], unique=False)
    op.create_table('nurse_shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('shift_name', sa.String(length=50), nullable=False),
    sa.Column('shift_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nurse_shifts_created_at'), 'nurse_shifts', ['created_at'], unique=False)
    op.create_index(op.f('ix_nurse_shifts_id'), 'nurse_shifts', ['id'], unique=False)
    op.create_index(op.f('ix_nurse_shifts_nurse_id'), 'nurse_shifts', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_nurse_shifts_shift_date'), 'nurse_shifts', ['shift_date'], unique=False)
    op.create_index(op.f('ix_nurse_shifts_shift_name'), 'nurse_shifts', ['shift_name'], unique=False)
    op.create_index(op.f('ix_nurse_shifts_status'), 'nurse_shifts', ['status'], unique=False)
    op.create_table('patient_diagnoses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('diagnosis', sa.Text(), nullable=False),
    sa.Column('symptoms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_diagnoses_created_at'), 'patient_diagnoses', ['created_at'], unique=False)
    op.create_index(op.f('ix_patient_diagnoses_id'), 'patient_diagnoses', ['id'], unique=False)
    op.create_index(op.f('ix_patient_diagnoses_patient_id'), 'patient_diagnoses', ['patient_id'], unique=True)
    op.create_table('treatment_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('treatment_plan', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_treatment_notes_created_at'), 'treatment_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_treatment_notes_id'), 'treatment_notes', ['id'], unique=False)
    op.create_index(op.f('ix_treatment_notes_patient_id'), 'treatment_notes', ['patient_id'], unique=False)
    op.create_table('nurse_handover_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('handover_date', sa.Date(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('pending_tasks', sa.Text(), nullable=True),
    sa.Column('patient_updates', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['nurse_shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nurse_handover_notes_created_at'), 'nurse_handover_notes', ['created_at'], unique=False)
    op.create_index(op.f('ix_nurse_handover_notes_handover_date'), 'nurse_handover_notes', ['handover_date'], unique=False)
    op.create_index(op.f('ix_nurse_handover_notes_id'), 'nurse_handover_notes', ['id'], unique=False)
    op.create_index(op.f('ix_nurse_handover_notes_nurse_id'), 'nurse_handover_notes', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_nurse_handover_notes_shift_id'), 'nurse_handover_notes', ['shift_id'], unique=False)
    op.create_index(op.f('ix_nurse_handover_notes_status'), 'nurse_handover_notes', ['status'], unique=False)
    op.create_table('nurse_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nurse_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['nurse_id'], ['nurses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shift_id'], ['nurse_shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nurse_notifications_created_at'), 'nurse_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_nurse_notifications_id'), 'nurse_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_nurse_notifications_notification_type'), 'nurse_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_nurse_notifications_nurse_id'), 'nurse_notifications', ['nurse_id'], unique=False)
    op.create_index(op.f('ix_nurse_notifications_patient_id'), 'nurse_notifications', ['patient_id'], unique=False)
    op.create_index(op.f('ix_nurse_notifications_priority'), 'nurse_notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_nurse_notifications_shift_id'), 'nurse_notifications', ['shift_id'], unique=False)
    op.create_index(op.f('ix_nurse_notifications_status'), 'nurse_notifications', ['status'], unique=False)
    op.alter_column('hospital_faqs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('hospital_faqs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_hospital_faqs_created_at'), 'hospital_faqs', ['created_at'], unique=False)
    op.create_index(op.f('ix_hospital_faqs_id'), 'hospital_faqs', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_faqs_is_active'), 'hospital_faqs', ['is_active'], unique=False)
    op.create_index(op.f('ix_hospital_faqs_is_deleted'), 'hospital_faqs', ['is_deleted'], unique=False)
    op.alter_column('hospital_policies', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('hospital_policies', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_hospital_policies_created_at'), 'hospital_policies', ['created_at'], unique=False)
    op.create_index(op.f('ix_hospital_policies_id'), 'hospital_policies', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_policies_is_active'), 'hospital_policies', ['is_active'], unique=False)
    op.create_index(op.f('ix_hospital_policies_is_deleted'), 'hospital_policies', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hospital_policies_language'), 'hospital_policies', ['language'], unique=False)
    op.alter_column('hospital_voice_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('hospital_voice_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_hospital_voice_configs_created_at'), 'hospital_voice_configs', ['created_at'], unique=False)
    op.create_index(op.f('ix_hospital_voice_configs_id'), 'hospital_voice_configs', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_voice_configs_is_active'), 'hospital_voice_configs', ['is_active'], unique=False)
    op.create_index(op.f('ix_hospital_voice_configs_is_deleted'), 'hospital_voice_configs', ['is_deleted'], unique=False)
    op.alter_column('hospital_voice_documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('hospital_voice_documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_hospital_voice_documents_created_at'), 'hospital_voice_documents', ['created_at'], unique=False)
    op.create_index(op.f('ix_hospital_voice_documents_id'), 'hospital_voice_documents', ['id'], unique=False)
    op.create_index(op.f('ix_hospital_voice_documents_is_active'), 'hospital_voice_documents', ['is_active'], unique=False)
    op.create_index(op.f('ix_hospital_voice_documents_is_deleted'), 'hospital_voice_documents', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_hospital_voice_documents_language'), 'hospital_voice_documents', ['language'], unique=False)
    op.alter_column('voice_callback_tickets', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('voice_callback_tickets', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.create_index(op.f('ix_voice_callback_tickets_call_id'), 'voice_callback_tickets', ['call_id'], unique=False)
    op.create_index(op.f('ix_voice_callback_tickets_created_at'), 'voice_callback_tickets', ['created_at'], unique=False)
    op.create_index(op.f('ix_voice_callback_tickets_hospital_id'), 'voice_callback_tickets', ['hospital_id'], unique=False)
    op.create_index(op.f('ix_voice_callback_tickets_id'), 'voice_callback_tickets', ['id'], unique=False)
    op.create_index(op.f('ix_voice_callback_tickets_patient_id'), 'voice_callback_tickets', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_callback_tickets_patient_id'), table_name='voice_callback_tickets')
    op.drop_index(op.f('ix_voice_callback_tickets_id'), table_name='voice_callback_tickets')
    op.drop_index(op.f('ix_voice_callback_tickets_hospital_id'), table_name='voice_callback_tickets')
    op.drop_index(op.f('ix_voice_callback_tickets_created_at'), table_name='voice_callback_tickets')
    op.drop_index(op.f('ix_voice_callback_tickets_call_id'), table_name='voice_callback_tickets')
    op.alter_column('voice_callback_tickets', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('voice_callback_tickets', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_hospital_voice_documents_language'), table_name='hospital_voice_documents')
    op.drop_index(op.f('ix_hospital_voice_documents_is_deleted'), table_name='hospital_voice_documents')
    op.drop_index(op.f('ix_hospital_voice_documents_is_active'), table_name='hospital_voice_documents')
    op.drop_index(op.f('ix_hospital_voice_documents_id'), table_name='hospital_voice_documents')
    op.drop_index(op.f('ix_hospital_voice_documents_created_at'), table_name='hospital_voice_documents')
    op.alter_column('hospital_voice_documents', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('hospital_voice_documents', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_hospital_voice_configs_is_deleted'), table_name='hospital_voice_configs')
    op.drop_index(op.f('ix_hospital_voice_configs_is_active'), table_name='hospital_voice_configs')
    op.drop_index(op.f('ix_hospital_voice_configs_id'), table_name='hospital_voice_configs')
    op.drop_index(op.f('ix_hospital_voice_configs_created_at'), table_name='hospital_voice_configs')
    op.alter_column('hospital_voice_configs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('hospital_voice_configs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_hospital_policies_language'), table_name='hospital_policies')
    op.drop_index(op.f('ix_hospital_policies_is_deleted'), table_name='hospital_policies')
    op.drop_index(op.f('ix_hospital_policies_is_active'), table_name='hospital_policies')
    op.drop_index(op.f('ix_hospital_policies_id'), table_name='hospital_policies')
    op.drop_index(op.f('ix_hospital_policies_created_at'), table_name='hospital_policies')
    op.alter_column('hospital_policies', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('hospital_policies', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_hospital_faqs_is_deleted'), table_name='hospital_faqs')
    op.drop_index(op.f('ix_hospital_faqs_is_active'), table_name='hospital_faqs')
    op.drop_index(op.f('ix_hospital_faqs_id'), table_name='hospital_faqs')
    op.drop_index(op.f('ix_hospital_faqs_created_at'), table_name='hospital_faqs')
    op.alter_column('hospital_faqs', 'updated_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.alter_column('hospital_faqs', 'created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    op.drop_index(op.f('ix_nurse_notifications_status'), table_name='nurse_notifications')
    op.drop_index(op.f('ix_nurse_notifications_shift_id'), table_name='nurse_notifications')
    op.drop_index(op.f('ix_nurse_notifications_priority'), table_name='nurse_notifications')
    op.drop_index(op.f('ix_nurse_notifications_patient_id'), table_name='nurse_notifications')
    op.drop_index(op.f('ix_nurse_notifications_nurse_id'), table_name='nurse_notifications')
    op.drop_index(op.f('ix_nurse_notifications_notification_type'), table_name='nurse_notifications')
    op.drop_index(op.f('ix_nurse_notifications_id'), table_name='nurse_notifications')
    op.drop_index(op.f('ix_nurse_notifications_created_at'), table_name='nurse_notifications')
    op.drop_table('nurse_notifications')
    op.drop_index(op.f('ix_nurse_handover_notes_status'), table_name='nurse_handover_notes')
    op.drop_index(op.f('ix_nurse_handover_notes_shift_id'), table_name='nurse_handover_notes')
    op.drop_index(op.f('ix_nurse_handover_notes_nurse_id'), table_name='nurse_handover_notes')
    op.drop_index(op.f('ix_nurse_handover_notes_id'), table_name='nurse_handover_notes')
    op.drop_index(op.f('ix_nurse_handover_notes_handover_date'), table_name='nurse_handover_notes')
    op.drop_index(op.f('ix_nurse_handover_notes_created_at'), table_name='nurse_handover_notes')
    op.drop_table('nurse_handover_notes')
    op.drop_index(op.f('ix_treatment_notes_patient_id'), table_name='treatment_notes')
    op.drop_index(op.f('ix_treatment_notes_id'), table_name='treatment_notes')
    op.drop_index(op.f('ix_treatment_notes_created_at'), table_name='treatment_notes')
    op.drop_table('treatment_notes')
    op.drop_index(op.f('ix_patient_diagnoses_patient_id'), table_name='patient_diagnoses')
    op.drop_index(op.f('ix_patient_diagnoses_id'), table_name='patient_diagnoses')
    op.drop_index(op.f('ix_patient_diagnoses_created_at'), table_name='patient_diagnoses')
    op.drop_table('patient_diagnoses')
    op.drop_index(op.f('ix_nurse_shifts_status'), table_name='nurse_shifts')
    op.drop_index(op.f('ix_nurse_shifts_shift_name'), table_name='nurse_shifts')
    op.drop_index(op.f('ix_nurse_shifts_shift_date'), table_name='nurse_shifts')
    op.drop_index(op.f('ix_nurse_shifts_nurse_id'), table_name='nurse_shifts')
    op.drop_index(op.f('ix_nurse_shifts_id'), table_name='nurse_shifts')
    op.drop_index(op.f('ix_nurse_shifts_created_at'), table_name='nurse_shifts')
    op.drop_table('nurse_shifts')
    op.drop_index(op.f('ix_nurse_patient_assignments_status'), table_name='nurse_patient_assignments')
    op.drop_index(op.f('ix_nurse_patient_assignments_patient_status'), table_name='nurse_patient_assignments')
    op.drop_index(op.f('ix_nurse_patient_assignments_patient_id'), table_name='nurse_patient_assignments')
    op.drop_index(op.f('ix_nurse_patient_assignments_nurse_id'), table_name='nurse_patient_assignments')
    op.drop_index(op.f('ix_nurse_patient_assignments_id'), table_name='nurse_patient_assignments')
    op.drop_index(op.f('ix_nurse_patient_assignments_created_at'), table_name='nurse_patient_assignments')
    op.drop_table('nurse_patient_assignments')
    op.drop_index(op.f('ix_nurse_attendance_status'), table_name='nurse_attendance')
    op.drop_index(op.f('ix_nurse_attendance_nurse_id'), table_name='nurse_attendance')
    op.drop_index(op.f('ix_nurse_attendance_id'), table_name='nurse_attendance')
    op.drop_index(op.f('ix_nurse_attendance_created_at'), table_name='nurse_attendance')
    op.drop_index(op.f('ix_nurse_attendance_attendance_date'), table_name='nurse_attendance')
    op.drop_table('nurse_attendance')
    op.drop_index(op.f('ix_doctor_medical_records_patient_id'), table_name='doctor_medical_records')
    op.drop_index(op.f('ix_doctor_medical_records_id'), table_name='doctor_medical_records')
    op.drop_index(op.f('ix_doctor_medical_records_doctor_id'), table_name='doctor_medical_records')
    op.drop_index(op.f('ix_doctor_medical_records_created_at'), table_name='doctor_medical_records')
    op.drop_table('doctor_medical_records')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_reference_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_reference_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_priority'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_deleted'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
