"""add appointment settings

Revision ID: 5eb3842f76f8
Revises: 161cac564015
Create Date: 2026-07-23 07:37:25.698551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '5eb3842f76f8'
down_revision: Union[str, None] = '161cac564015'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('operation_mode', sa.Enum('fixed_hours', 'twenty_four_seven', 'shift_based', 'custom', name='operationmode'), server_default=sa.text("'fixed_hours'"), nullable=False),
    sa.Column('slot_duration_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('working_start_time', sa.Time(), server_default=sa.text("'09:00:00'"), nullable=False),
    sa.Column('working_end_time', sa.Time(), server_default=sa.text("'18:00:00'"), nullable=False),
    sa.Column('lunch_break_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('lunch_start_time', sa.Time(), nullable=True),
    sa.Column('lunch_end_time', sa.Time(), nullable=True),
    sa.Column('max_advance_booking_days', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('allow_overlapping', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('auto_cancel_no_show_minutes', sa.Integer(), server_default=sa.text('30'), nullable=False),
    sa.Column('weekend_booking_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False),
    sa.Column('buffer_between_slots_minutes', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('allow_walk_in', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_settings_created_at'), 'appointment_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_appointment_settings_hospital_id'), 'appointment_settings', ['hospital_id'], unique=True)
    op.create_index(op.f('ix_appointment_settings_id'), 'appointment_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment_settings')
    # ### end Alembic commands ###
