"""add_user_preference_settings_fields

Revision ID: 6649f4fddb98
Revises: 65c4e208c1be
Create Date: 2026-08-12 21:34:03.603646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '6649f4fddb98'
down_revision: Union[str, None] = '65c4e208c1be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('compact_mode', sa.Boolean(), server_default=sa.text('0'), nullable=False))
    op.add_column('user_preferences', sa.Column('push_notifications', sa.Boolean(), server_default=sa.text('1'), nullable=False))
    op.add_column('user_preferences', sa.Column('critical_emergency_alerts', sa.Boolean(), server_default=sa.text('1'), nullable=False))

    op.create_table('push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=False),
    sa.Column('p256dh', sa.String(length=255), nullable=False),
    sa.Column('auth', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'endpoint', name='uix_push_sub_user_endpoint')
    )
    op.create_index(op.f('ix_push_subscriptions_created_at'), 'push_subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_id'), 'push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_is_active'), 'push_subscriptions', ['is_active'], unique=False)
    op.create_index(op.f('ix_push_subscriptions_user_id'), 'push_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_push_subscriptions_user_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_is_active'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_id'), table_name='push_subscriptions')
    op.drop_index(op.f('ix_push_subscriptions_created_at'), table_name='push_subscriptions')
    op.drop_table('push_subscriptions')

    op.drop_column('user_preferences', 'critical_emergency_alerts')
    op.drop_column('user_preferences', 'push_notifications')
    op.drop_column('user_preferences', 'compact_mode')
    # ### end Alembic commands ###
