"""add_diagnosis_to_patients

Revision ID: 7418f4b54f93
Revises: 5e045bdb36b2
Create Date: 2026-07-22 12:44:50.815586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '7418f4b54f93'
down_revision: Union[str, None] = '5e045bdb36b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('diagnosis', sa.Text(), server_default='', nullable=False))
    
    # Safely check and add columns/indexes to appointments
    conn = op.get_bind()
    from sqlalchemy.engine import reflection
    inspector = reflection.Inspector.from_engine(conn)
    existing_cols = [c["name"] for c in inspector.get_columns("appointments")]
    
    if 'check_in_time' not in existing_cols:
        op.add_column('appointments', sa.Column('check_in_time', sa.DateTime(), nullable=True))
    if 'check_out_time' not in existing_cols:
        op.add_column('appointments', sa.Column('check_out_time', sa.DateTime(), nullable=True))
    if 'queue_token' not in existing_cols:
        op.add_column('appointments', sa.Column('queue_token', sa.String(length=50), nullable=True))
        op.create_index(op.f('ix_appointments_queue_token'), 'appointments', ['queue_token'], unique=False)
    if 'queue_status' not in existing_cols:
        op.add_column('appointments', sa.Column('queue_status', sa.String(length=50), nullable=True))
        op.create_index(op.f('ix_appointments_queue_status'), 'appointments', ['queue_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Safely drop columns/indexes from appointments
    conn = op.get_bind()
    from sqlalchemy.engine import reflection
    inspector = reflection.Inspector.from_engine(conn)
    existing_cols = [c["name"] for c in inspector.get_columns("appointments")]
    existing_indexes = [idx["name"] for idx in inspector.get_indexes("appointments")]

    if 'ix_appointments_queue_status' in existing_indexes:
        op.drop_index(op.f('ix_appointments_queue_status'), table_name='appointments')
    if 'ix_appointments_queue_token' in existing_indexes:
        op.drop_index(op.f('ix_appointments_queue_token'), table_name='appointments')
    
    if 'queue_status' in existing_cols:
        op.drop_column('appointments', 'queue_status')
    if 'queue_token' in existing_cols:
        op.drop_column('appointments', 'queue_token')
    if 'check_out_time' in existing_cols:
        op.drop_column('appointments', 'check_out_time')
    if 'check_in_time' in existing_cols:
        op.drop_column('appointments', 'check_in_time')
        
    op.drop_column('patients', 'diagnosis')
    # ### end Alembic commands ###
