"""refactor_staff_model

Revision ID: 842a57bf1313
Revises: a609ea3b360d
Create Date: 2026-06-12 15:15:52.163153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

revision: str = '842a57bf1313'
down_revision: Union[str, None] = 'a609ea3b360d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    columns = [col['name'] for col in inspector.get_columns('staff')]
    if 'full_name' in columns:
        op.drop_column('staff', 'full_name')
    if 'staff_code' in columns:
        op.drop_column('staff', 'staff_code')
    if 'role_name' in columns:
        op.drop_column('staff', 'role_name')

    op.add_column('staff', sa.Column('full_name', sa.String(length=200), nullable=False))
    op.add_column('staff', sa.Column('staff_code', sa.String(length=50), nullable=False))
    op.add_column('staff', sa.Column('role_name', sa.String(length=50), nullable=False))
    op.alter_column('staff', 'status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.Integer(),
               existing_nullable=False)

    # Drop foreign key constraint first if it exists
    fks = [fk['name'] for fk in inspector.get_foreign_keys('staff')]
    if 'staff_ibfk_2' in fks:
        op.drop_constraint('staff_ibfk_2', 'staff', type_='foreignkey')

    # Drop old indexes if they exist
    indexes = [idx['name'] for idx in inspector.get_indexes('staff')]
    for idx_name in ('ix_staff_employee_code', 'ix_staff_first_name', 'ix_staff_last_name', 'ix_staff_role_id'):
        if idx_name in indexes:
            op.drop_index(idx_name, table_name='staff')

    op.create_index(op.f('ix_staff_full_name'), 'staff', ['full_name'], unique=False)
    op.create_index(op.f('ix_staff_role_name'), 'staff', ['role_name'], unique=False)
    op.create_index(op.f('ix_staff_staff_code'), 'staff', ['staff_code'], unique=True)
    op.create_foreign_key(None, 'staff', 'roles', ['role_name'], ['name'])
    op.drop_column('staff', 'last_name')
    op.drop_column('staff', 'first_name')
    op.drop_column('staff', 'employee_code')
    op.drop_column('staff', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('role_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('staff', sa.Column('employee_code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False))
    op.add_column('staff', sa.Column('first_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.add_column('staff', sa.Column('last_name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    
    connection = op.get_bind()
    inspector = sa.inspect(connection)
    
    # Drop foreign key constraint
    for fk in inspector.get_foreign_keys('staff'):
        if 'role_name' in fk['constrained_columns']:
            op.drop_constraint(fk['name'], 'staff', type_='foreignkey')

    # Drop new indexes
    indexes = [idx['name'] for idx in inspector.get_indexes('staff')]
    for idx_name in ('ix_staff_staff_code', 'ix_staff_role_name', 'ix_staff_full_name'):
        if idx_name in indexes:
            op.drop_index(idx_name, table_name='staff')

    op.create_index(op.f('ix_staff_role_id'), 'staff', ['role_id'], unique=False)
    op.create_index(op.f('ix_staff_last_name'), 'staff', ['last_name'], unique=False)
    op.create_index(op.f('ix_staff_first_name'), 'staff', ['first_name'], unique=False)
    op.create_index(op.f('ix_staff_employee_code'), 'staff', ['employee_code'], unique=True)
    op.create_foreign_key('staff_ibfk_2', 'staff', 'roles', ['role_id'], ['id'])
    op.alter_column('staff', 'status',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)
    op.drop_column('staff', 'role_name')
    op.drop_column('staff', 'staff_code')
    op.drop_column('staff', 'full_name')
    # ### end Alembic commands ###
