"""add_billing_settings

Revision ID: beca753eae5d
Revises: 5eb3842f76f8
Create Date: 2026-07-24 14:14:59.065392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


revision: str = 'beca753eae5d'
down_revision: Union[str, None] = '5eb3842f76f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hospital_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=10), server_default=sa.text("'INR'"), nullable=False),
    sa.Column('currency_symbol', sa.String(length=5), server_default=sa.text("'₹'"), nullable=False),
    sa.Column('gst_percentage', sa.Float(), server_default=sa.text('18.0'), nullable=False),
    sa.Column('invoice_prefix', sa.String(length=10), server_default=sa.text("'BIL'"), nullable=False),
    sa.Column('receipt_prefix', sa.String(length=10), server_default=sa.text("'REC'"), nullable=False),
    sa.Column('default_payment_mode', sa.String(length=20), server_default=sa.text("'cash'"), nullable=False),
    sa.Column('round_off_rule', sa.String(length=20), server_default=sa.text("'nearest'"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_settings_created_at'), 'billing_settings', ['created_at'], unique=False)
    op.create_index(op.f('ix_billing_settings_hospital_id'), 'billing_settings', ['hospital_id'], unique=True)
    op.create_index(op.f('ix_billing_settings_id'), 'billing_settings', ['id'], unique=False)
    # ### end Alembic commands ###

    # Alter the ENUM column to use lowercase values (matching the Python Enum values).
    # In MySQL, altering the ENUM labels like this will automatically map the existing 
    # uppercase values (e.g., 'FIXED_HOURS') to their lowercase counterparts ('fixed_hours')
    # because the underlying integer indices remain the same.
    op.execute(
        "ALTER TABLE appointment_settings MODIFY COLUMN operation_mode "
        "ENUM('fixed_hours', 'twenty_four_seven', 'shift_based', 'custom') "
        "NOT NULL DEFAULT 'fixed_hours'"
    )

    op.alter_column(
        "samples",
        "volume",
        existing_type=mysql.FLOAT(),
        type_=sa.String(length=100),
        existing_nullable=True,
    )

    op.add_column(
        "purchases",
        sa.Column("received_by", sa.Integer(), nullable=True),
    )

    op.create_foreign_key(
        "fk_purchases_received_by_users",
        "purchases",
        "users",
        ["received_by"],
        ["id"],
    )


def downgrade() -> None:

    # 1. Remove FK
    op.drop_constraint(
        "fk_purchases_received_by_users",
        "purchases",
        type_="foreignkey",
    )

    # 2. Remove column
    op.drop_column(
        "purchases",
        "received_by",
    )

    # -------------------------

    # 3. samples.volume back to FLOAT
    op.alter_column(
        "samples",
        "volume",
        existing_type=sa.String(length=100),
        type_=mysql.FLOAT(),
        existing_nullable=True,
    )

    # Revert back to uppercase values if downgraded
    op.execute(
        "ALTER TABLE appointment_settings MODIFY COLUMN operation_mode "
        "ENUM('FIXED_HOURS', 'TWENTY_FOUR_SEVEN', 'SHIFT_BASED', 'CUSTOM') "
        "NOT NULL DEFAULT 'FIXED_HOURS'"
    )

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billing_settings')
    # ### end Alembic commands ###
