"""add_appointment_id_to_billings

Revision ID: c4ae81de4724
Revises: 4a59273b8083
Create Date: 2026-07-13 10:38:52.831821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

revision: str = 'c4ae81de4724'
down_revision: Union[str, None] = '4a59273b8083'
"""add_appointment_id_to_billings

Revision ID: c4ae81de4724
Revises: 4a59273b8083
Create Date: 2026-07-13 10:38:52.831821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from sqlalchemy.dialects import mysql

revision: str = 'c4ae81de4724'
down_revision: Union[str, None] = '4a59273b8083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('billings', sa.Column('appointment_id', sa.Integer(), nullable=True))
    # op.create_foreign_key(None, 'billings', 'appointments', ['appointment_id'], ['id'])
    # op.create_index(op.f('ix_clinical_records_created_at'), 'clinical_records', ['created_at'], unique=False)
    # op.create_index(op.f('ix_doctor_medical_records_created_at'), 'doctor_medical_records', ['created_at'], unique=False)
    # op.create_index(op.f('ix_icu_devices_id'), 'icu_devices', ['id'], unique=False)
    # op.create_index(op.f('ix_icu_telemetry_alerts_id'), 'icu_telemetry_alerts', ['id'], unique=False)
    # op.drop_index(op.f('ix_icu_vital_readings_bed_recorded'), table_name='icu_vital_readings')
    # op.create_index(op.f('ix_icu_vital_readings_id'), 'icu_vital_readings', ['id'], unique=False)
    # op.alter_column('pharmacy_invoices', 'discount_percentage',
    #            existing_type=mysql.FLOAT(),
    #            nullable=False)
    # op.alter_column('pharmacy_invoices', 'tax_percentage',
    #            existing_type=mysql.FLOAT(),
    #            nullable=False)
    # op.alter_column('pharmacy_invoices', 'tax_amount',
    #            existing_type=mysql.FLOAT(),
    #            nullable=False)
    # op.alter_column('staff', 'department_id',
    #            existing_type=mysql.INTEGER(),
    #            nullable=True)
    # op.create_index(op.f('ix_staff_created_at'), 'staff', ['created_at'], unique=False)
    from sqlalchemy import inspect
    bind = op.get_bind()
    insp = inspect(bind)
    fks = insp.get_foreign_keys('subscriptions')
    for fk in fks:
        if 'hospital_id' in fk['constrained_columns']:
            op.drop_constraint(fk['name'], 'subscriptions', type_='foreignkey')
    
    indexes = insp.get_indexes('subscriptions')
    index_names = [idx['name'] for idx in indexes]
    if 'ix_subscriptions_hospital_id' in index_names:
        op.drop_index('ix_subscriptions_hospital_id', table_name='subscriptions')
        
    columns = [col['name'] for col in insp.get_columns('subscriptions')]
    if 'hospital_id' in columns:
        op.drop_column('subscriptions', 'hospital_id')
    op.create_index(op.f('ix_transaction_history_created_at'), 'transaction_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_transaction_history_is_deleted'), 'transaction_history', ['is_deleted'], unique=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_history_is_deleted'), table_name='transaction_history')
    op.drop_index(op.f('ix_transaction_history_created_at'), table_name='transaction_history')
    op.add_column('subscriptions', sa.Column('hospital_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('subscriptions_ibfk_1'), 'subscriptions', 'hospitals', ['hospital_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_subscriptions_hospital_id'), 'subscriptions', ['hospital_id'], unique=False)
    op.drop_index(op.f('ix_staff_created_at'), table_name='staff')
    op.alter_column('staff', 'department_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('pharmacy_invoices', 'tax_amount',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('pharmacy_invoices', 'tax_percentage',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('pharmacy_invoices', 'discount_percentage',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_index(op.f('ix_icu_vital_readings_id'), table_name='icu_vital_readings')
    op.create_index(op.f('ix_icu_vital_readings_bed_recorded'), 'icu_vital_readings', ['bed_id', 'recorded_at'], unique=False)
    op.drop_index(op.f('ix_icu_telemetry_alerts_id'), table_name='icu_telemetry_alerts')
    op.drop_index(op.f('ix_icu_devices_id'), table_name='icu_devices')
    op.drop_index(op.f('ix_doctor_medical_records_created_at'), table_name='doctor_medical_records')
    op.drop_index(op.f('ix_clinical_records_created_at'), table_name='clinical_records')
    op.drop_constraint(None, 'billings', type_='foreignkey')
    op.drop_column('billings', 'appointment_id')
    # ### end Alembic commands ###
